// Code generated by generate_enum; DO NOT EDIT.

package arch

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// Status is an enumerated type
type Status uint8

const (
	// X86_64 is an enumeration for arch.Status
	X86_64 Status = iota + 1
	// I686 is an enumeration for Status
	I686
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	X86_64.String(),
	I686.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "x86_64":
		return X86_64, nil
	case "i686":
		return I686, nil
	}
	var zero Status
	return zero, fmt.Errorf("%s is not a valid arch.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case X86_64:
		return []byte("x86_64"), nil
	case I686:
		return []byte("i686"), nil
	}
	return nil, fmt.Errorf("%d is not a valid arch.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return &json.UnmarshalTypeError{
			Value: name,
			Type:  reflect.TypeOf(i),
		}
	}
	*i = tmp
	return nil
}
