// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// AccountAPIPath returns the relative URL path to the Account endpoint
	AccountAPIPath = "accounts"
)

// Accounts returns the collection view for Account
func (c *Client) Accounts(ctx context.Context) ([]Account, error) {
	return APIGetCollection[Account](ctx, c, AccountAPIPath)
}

// Account retrieves a detailed view of one resource
func (c *Client) Account(ctx context.Context, identifier string) (*Account, error) {
	return APIGet[Account](ctx, c, path.Join(AccountAPIPath, identifier))
}

// UpdateAccount updates an existing resources's attributes. Not all
// attributes can be changed (such as ID).
//
// It takes an instance of AccountOptions. Specify the resource you
// want to update using the ID field.
func (c *Client) UpdateAccount(ctx context.Context, updateAccount *AccountOptions) (*Account, error) {
	return APIPut[Account](ctx, c, path.Join(AccountAPIPath, updateAccount.ID), updateAccount)
}

// ResetAccountPassword resets the password in Account, returning it
// in the returned resource. This is the only time the new password is
// available in plaintext.
func (c *Client) ResetAccountPassword(ctx context.Context, identifier string) (*Account, error) {
	return APIPost[Account](ctx, c, path.Join(AccountAPIPath, identifier, "reset_ftp_password"), nil)
}
