// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// APIClientAPIPath returns the relative URL path to the APIClient endpoint
	APIClientAPIPath = "api_clients"
)

// APIClients returns the collection view for APIClient
func (c *Client) APIClients(ctx context.Context) ([]APIClient, error) {
	return APIGetCollection[APIClient](ctx, c, APIClientAPIPath)
}

// APIClient retrieves a detailed view of one resource
func (c *Client) APIClient(ctx context.Context, identifier string) (*APIClient, error) {
	return APIGet[APIClient](ctx, c, path.Join(APIClientAPIPath, identifier))
}

// CreateAPIClient creates a new resource from the supplied option map.
//
// It takes an instance of APIClientOptions. Not all attributes can be
// specified at create time (such as ID, which is allocated for you).
func (c *Client) CreateAPIClient(ctx context.Context, newAPIClient *APIClientOptions) (*APIClient, error) {
	return APIPost[APIClient](ctx, c, APIClientAPIPath, newAPIClient)
}

// UpdateAPIClient updates an existing resources's attributes. Not all
// attributes can be changed (such as ID).
//
// It takes an instance of APIClientOptions. Specify the resource you
// want to update using the ID field.
func (c *Client) UpdateAPIClient(ctx context.Context, updateAPIClient *APIClientOptions) (*APIClient, error) {
	return APIPut[APIClient](ctx, c, path.Join(APIClientAPIPath, updateAPIClient.ID), updateAPIClient)
}

// DestroyAPIClient destroys an existing resource.
func (c *Client) DestroyAPIClient(ctx context.Context, identifier string) error {
	return APIDelete(ctx, c, path.Join(APIClientAPIPath, identifier))
}
