// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/v3/assert"
)

func TestAPIClients(t *testing.T) {
	instance := testAll[APIClient](
		t,
		(*Client).APIClients,
		"APIClient",
		"api_clients",
		"APIClients",
	)
	assert.Equal(t, instance.ID, "cli-dsse2")
}

func TestAPIClient(t *testing.T) {
	instance := testInstance[APIClient](
		t,
		(*Client).APIClient,
		"APIClient",
		path.Join("api_clients", "cli-dsse2"),
		"api_client",
		"cli-dsse2",
	)
	assert.Equal(t, instance.ID, "cli-dsse2")
}

func TestCreateAPIClient(t *testing.T) {
	newResource := APIClientOptions{}
	instance := testModify[APIClient, APIClientOptions](
		t,
		(*Client).CreateAPIClient,
		newResource,
		"api_client",
		"POST",
		path.Join("api_clients"),
		"{}",
	)
	assert.Equal(t, instance.ID, "cli-dsse2")
}

func TestUpdateAPIClient(t *testing.T) {
	updatedResource := APIClientOptions{ID: "cli-dsse2"}
	instance := testModify[APIClient, APIClientOptions](
		t,
		(*Client).UpdateAPIClient,
		updatedResource,
		"api_client",
		"PUT",
		path.Join("api_clients", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}

func TestDestroyAPIClient(t *testing.T) {
	deletedResource := testModify[APIClient, string](
		t,
		(*Client).DestroyAPIClient,
		"cli-dsse2",
		"api_client",
		"DELETE",
		path.Join("api_clients", "cli-dsse2"),
		"",
	)
	assert.Equal(t, deletedResource.ID, "cli-dsse2")
}

func TestResetAPIClientPassword(t *testing.T) {
	instance := testModify[APIClient, string](
		t,
		(*Client).ResetAPIClientPassword,
		"cli-dsse2",
		"api_client",
		"POST",
		path.Join("api_clients", "cli-dsse2", "reset_secret"),
		"",
	)
	assert.Equal(t, instance.ID, "cli-dsse2")
}
