// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// CollaborationAPIPath returns the relative URL path to the Collaboration endpoint
	CollaborationAPIPath = "collaborations"
)

// Collaborations returns the collection view for Collaboration
func (c *Client) Collaborations(ctx context.Context) ([]Collaboration, error) {
	return APIGetCollection[Collaboration](ctx, c, CollaborationAPIPath)
}

// Collaboration retrieves a detailed view of one resource
func (c *Client) Collaboration(ctx context.Context, identifier string) (*Collaboration, error) {
	return APIGet[Collaboration](ctx, c, path.Join(CollaborationAPIPath, identifier))
}

// CreateCollaboration creates a new resource from the supplied option map.
//
// It takes an instance of CollaborationOptions. Not all attributes can be
// specified at create time (such as ID, which is allocated for you).
func (c *Client) CreateCollaboration(ctx context.Context, newCollaboration *CollaborationOptions) (*Collaboration, error) {
	return APIPost[Collaboration](ctx, c, CollaborationAPIPath, newCollaboration)
}

// DestroyCollaboration destroys an existing resource.
func (c *Client) DestroyCollaboration(ctx context.Context, identifier string) error {
	return APIDelete(ctx, c, path.Join(CollaborationAPIPath, identifier))
}
