// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// DatabaseServerTypeAPIPath returns the relative URL path to the DatabaseServerType endpoint
	DatabaseServerTypeAPIPath = "database_types"
)

// DatabaseServerTypes returns the collection view for DatabaseServerType
func (c *Client) DatabaseServerTypes(ctx context.Context) ([]DatabaseServerType, error) {
	return APIGetCollection[DatabaseServerType](ctx, c, DatabaseServerTypeAPIPath)
}

// DatabaseServerType retrieves a detailed view of one resource
func (c *Client) DatabaseServerType(ctx context.Context, identifier string) (*DatabaseServerType, error) {
	return APIGet[DatabaseServerType](ctx, c, path.Join(DatabaseServerTypeAPIPath, identifier))
}
