// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// DatabaseServerAPIPath returns the relative URL path to the DatabaseServer endpoint
	DatabaseServerAPIPath = "database_servers"
)

// DatabaseServers returns the collection view for DatabaseServer
func (c *Client) DatabaseServers(ctx context.Context) ([]DatabaseServer, error) {
	return APIGetCollection[DatabaseServer](ctx, c, DatabaseServerAPIPath)
}

// DatabaseServer retrieves a detailed view of one resource
func (c *Client) DatabaseServer(ctx context.Context, identifier string) (*DatabaseServer, error) {
	return APIGet[DatabaseServer](ctx, c, path.Join(DatabaseServerAPIPath, identifier))
}

// CreateDatabaseServer creates a new resource from the supplied option map.
//
// It takes an instance of DatabaseServerOptions. Not all attributes can be
// specified at create time (such as ID, which is allocated for you).
func (c *Client) CreateDatabaseServer(ctx context.Context, newDatabaseServer DatabaseServerOptions) (*DatabaseServer, error) {
	return APIPost[DatabaseServer](ctx, c, DatabaseServerAPIPath, newDatabaseServer)
}

// UpdateDatabaseServer updates an existing resources's attributes. Not all
// attributes can be changed (such as ID).
//
// It takes an instance of DatabaseServerOptions. Specify the resource you
// want to update using the ID field.
func (c *Client) UpdateDatabaseServer(ctx context.Context, updateDatabaseServer DatabaseServerOptions) (*DatabaseServer, error) {
	return APIPut[DatabaseServer](ctx, c, path.Join(DatabaseServerAPIPath, updateDatabaseServer.ID), updateDatabaseServer)
}

// DestroyDatabaseServer destroys an existing resource.
func (c *Client) DestroyDatabaseServer(ctx context.Context, identifier string) (*DatabaseServer, error) {
	return APIDelete[DatabaseServer](ctx, c, path.Join(DatabaseServerAPIPath, identifier))
}

// LockDatabaseServer locks a resource against destroy requests
func (c *Client) LockDatabaseServer(ctx context.Context, identifier string) (*DatabaseServer, error) {
	return APIPut[DatabaseServer](ctx, c, path.Join(DatabaseServerAPIPath, identifier, "lock_resource"), nil)
}

// UnlockDatabaseServer unlocks a resource, re-enabling destroy requests
func (c *Client) UnlockDatabaseServer(ctx context.Context, identifier string) (*DatabaseServer, error) {
	return APIPut[DatabaseServer](ctx, c, path.Join(DatabaseServerAPIPath, identifier, "unlock_resource"), nil)
}

// CreatedAt implements the CreateDated interface for DatabaseServer
func (s DatabaseServer) CreatedAtUnix() int64 {
	return s.CreatedAt.Unix()
}

// ResetDatabaseServerPassword resets the password in DatabaseServer, returning it
// in the returned resource. This is the only time the new password is
// available in plaintext.
func (c *Client) ResetDatabaseServerPassword(ctx context.Context, identifier string) (*DatabaseServer, error) {
	return APIPost[DatabaseServer](ctx, c, path.Join(DatabaseServerAPIPath, identifier, "reset_password"), nil)
}
