// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/v3/assert"
)

func TestDatabaseServers(t *testing.T) {
	instance := testAll[DatabaseServer](
		t,
		(*Client).DatabaseServers,
		"DatabaseServer",
		"database_servers",
		"DatabaseServers",
	)
	assert.Equal(t, instance.ID, "dbs-123ab")
}

func TestDatabaseServer(t *testing.T) {
	instance := testInstance[DatabaseServer](
		t,
		(*Client).DatabaseServer,
		"DatabaseServer",
		path.Join("database_servers", "dbs-123ab"),
		"database_server",
		"dbs-123ab",
	)
	assert.Equal(t, instance.ID, "dbs-123ab")
}

func TestCreateDatabaseServer(t *testing.T) {
	newResource := DatabaseServerOptions{}
	instance := testModify[DatabaseServer, *DatabaseServerOptions](
		t,
		(*Client).CreateDatabaseServer,
		&newResource,
		"database_server",
		"POST",
		path.Join("database_servers"),
		"{}",
	)
	assert.Equal(t, instance.ID, "dbs-123ab")
}

func TestUpdateDatabaseServer(t *testing.T) {
	updatedResource := DatabaseServerOptions{ID: "dbs-123ab"}
	instance := testModify[DatabaseServer, *DatabaseServerOptions](
		t,
		(*Client).UpdateDatabaseServer,
		&updatedResource,
		"database_server",
		"PUT",
		path.Join("database_servers", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}

func TestDestroyDatabaseServer(t *testing.T) {
	testCommand(
		t,
		(*Client).DestroyDatabaseServer,
		"dbs-123ab",
		"DELETE",
		path.Join("database_servers", "dbs-123ab"),
	)
}

func TestLockDatabaseServer(t *testing.T) {
	testCommand(
		t,
		(*Client).LockDatabaseServer,
		"dbs-123ab",
		"PUT",
		path.Join("database_servers", "dbs-123ab", "lock_resource"),
	)
}

func TestUnlockDatabaseServer(t *testing.T) {
	testCommand(
		t,
		(*Client).UnlockDatabaseServer,
		"dbs-123ab",
		"PUT",
		path.Join("database_servers", "dbs-123ab", "unlock_resource"),
	)
}

func TestResetDatabaseServerPassword(t *testing.T) {
	instance := testModify[DatabaseServer, string](
		t,
		(*Client).ResetDatabaseServerPassword,
		"dbs-123ab",
		"database_server",
		"POST",
		path.Join("database_servers", "dbs-123ab", "reset_password"),
		"",
	)
	assert.Equal(t, instance.ID, "dbs-123ab")
}
