// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// FirewallPolicyAPIPath returns the relative URL path to the FirewallPolicy endpoint
	FirewallPolicyAPIPath = "firewall_policies"
)

// FirewallPolicies returns the collection view for FirewallPolicy
func (c *Client) FirewallPolicies(ctx context.Context) ([]FirewallPolicy, error) {
	return APIGetCollection[FirewallPolicy](ctx, c, FirewallPolicyAPIPath)
}

// FirewallPolicy retrieves a detailed view of one resource
func (c *Client) FirewallPolicy(ctx context.Context, identifier string) (*FirewallPolicy, error) {
	return APIGet[FirewallPolicy](ctx, c, path.Join(FirewallPolicyAPIPath, identifier))
}

// CreateFirewallPolicy creates a new resource from the supplied option map.
//
// It takes an instance of FirewallPolicyOptions. Not all attributes can be
// specified at create time (such as ID, which is allocated for you).
func (c *Client) CreateFirewallPolicy(ctx context.Context, newFirewallPolicy *FirewallPolicyOptions) (*FirewallPolicy, error) {
	return APIPost[FirewallPolicy](ctx, c, FirewallPolicyAPIPath, newFirewallPolicy)
}

// UpdateFirewallPolicy updates an existing resources's attributes. Not all
// attributes can be changed (such as ID).
//
// It takes an instance of FirewallPolicyOptions. Specify the resource you
// want to update using the ID field.
func (c *Client) UpdateFirewallPolicy(ctx context.Context, updateFirewallPolicy *FirewallPolicyOptions) (*FirewallPolicy, error) {
	return APIPut[FirewallPolicy](ctx, c, path.Join(FirewallPolicyAPIPath, updateFirewallPolicy.ID), updateFirewallPolicy)
}

// DestroyFirewallPolicy destroys an existing resource.
func (c *Client) DestroyFirewallPolicy(ctx context.Context, identifier string) (*FirewallPolicy, error) {
	return APIDelete[FirewallPolicy](ctx, c, path.Join(FirewallPolicyAPIPath, identifier))
}
