// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/assert"
)

func TestFirewallRules(t *testing.T) {
	instance := testAll[FirewallRule](
		t,
		(*Client).FirewallRules,
		"FirewallRule",
		"firewall_rules",
		"FirewallRules",
	)
	assert.Equal(t, instance.ID, "fwr-k32ls")
}

func TestFirewallRule(t *testing.T) {
	instance := testInstance[FirewallRule](
		t,
		(*Client).FirewallRule,
		"FirewallRule",
		path.Join("firewall_rules", "fwr-k32ls"),
		"firewall_rule",
		"fwr-k32ls",
	)
	assert.Equal(t, instance.ID, "fwr-k32ls")
}

func TestCreateFirewallRule(t *testing.T) {
	newResource := FirewallRuleOptions{}
	instance := testModify[FirewallRule, FirewallRuleOptions](
		t,
		(*Client).CreateFirewallRule,
		&newResource,
		"firewall_rule",
		"POST",
		path.Join("firewall_rules"),
		"{}",
	)
	assert.Equal(t, instance.ID, "fwr-k32ls")
}

func TestUpdateFirewallRule(t *testing.T) {
	updatedResource := FirewallRuleOptions{ID: "fwr-k32ls"}
	instance := testModify[FirewallRule, FirewallRuleOptions](
		t,
		(*Client).UpdateFirewallRule,
		&updatedResource,
		"firewall_rule",
		"PUT",
		path.Join("firewall_rules", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}

func TestDestroyFirewallRule(t *testing.T) {
	testCommand(
		t,
		(*Client).DestroyFirewallRule,
		"fwr-k32ls",
		"DELETE",
		path.Join("firewall_rules", "fwr-k32ls"),
	)
}
