// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/assert"
)

func TestFirewallPolicies(t *testing.T) {
	instance := testAll[FirewallPolicy](
		t,
		(*Client).FirewallPolicies,
		"FirewallPolicy",
		"firewall_policies",
		"FirewallPolicies",
	)
	assert.Equal(t, instance.ID, "fwp-j3654")
}

func TestFirewallPolicy(t *testing.T) {
	instance := testInstance[FirewallPolicy](
		t,
		(*Client).FirewallPolicy,
		"FirewallPolicy",
		path.Join("firewall_policies", "fwp-j3654"),
		"firewall_policy",
		"fwp-j3654",
	)
	assert.Equal(t, instance.ID, "fwp-j3654")
}

func TestCreateFirewallPolicy(t *testing.T) {
	newResource := FirewallPolicyOptions{}
	instance := testModify[FirewallPolicy, FirewallPolicyOptions](
		t,
		(*Client).CreateFirewallPolicy,
		&newResource,
		"firewall_policy",
		"POST",
		path.Join("firewall_policies"),
		"{}",
	)
	assert.Equal(t, instance.ID, "fwp-j3654")
}

func TestUpdateFirewallPolicy(t *testing.T) {
	updatedResource := FirewallPolicyOptions{ID: "fwp-j3654"}
	instance := testModify[FirewallPolicy, FirewallPolicyOptions](
		t,
		(*Client).UpdateFirewallPolicy,
		&updatedResource,
		"firewall_policy",
		"PUT",
		path.Join("firewall_policies", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}

func TestDestroyFirewallPolicy(t *testing.T) {
	testCommand(
		t,
		(*Client).DestroyFirewallPolicy,
		"fwp-j3654",
		"DELETE",
		path.Join("firewall_policies", "fwp-j3654"),
	)
}
