// Code generated by go generate; DO NOT EDIT.

package brightbox

import "context"
import "path"

const (
	// InterfaceAPIPath returns the relative URL path to the Interface endpoint
	InterfaceAPIPath = "interfaces"
)

// Interfaces returns the collection view for Interface
func (c *Client) Interfaces(ctx context.Context) ([]Interface, error) {
	return APIGetCollection[Interface](ctx, c, InterfaceAPIPath)
}

// Interface retrieves a detailed view of one resource
func (c *Client) Interface(ctx context.Context, identifier string) (*Interface, error) {
	return APIGet[Interface](ctx, c, path.Join(InterfaceAPIPath, identifier))
}
