// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/assert"
)

func TestInterfaces(t *testing.T) {
	instance := testAll[Interface](
		t,
		(*Client).Interfaces,
		"Interface",
		"interfaces",
		"Interfaces",
	)
	assert.Equal(t, instance.ID, "int-ds42k")
}

func TestInterface(t *testing.T) {
	instance := testInstance[Interface](
		t,
		(*Client).Interface,
		"Interface",
		path.Join("interfaces", "int-ds42k"),
		"interface",
		"int-ds42k",
	)
	assert.Equal(t, instance.ID, "int-ds42k")
}
