// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"
	"time"

	"gotest.tools/v3/assert"
)

func TestServers(t *testing.T) {
	instance := testAll[Server](
		t,
		(*Client).Servers,
		"Server",
		"servers",
		"Servers",
	)
	assert.Equal(t, instance.ID, "srv-lv426")
}

func TestServer(t *testing.T) {
	instance := testInstance[Server](
		t,
		(*Client).Server,
		"Server",
		path.Join("servers", "srv-lv426"),
		"server",
		"srv-lv426",
	)
	assert.Equal(t, instance.ID, "srv-lv426")
}

func TestCreateServer(t *testing.T) {
	newResource := ServerOptions{}
	instance := testModify[Server, ServerOptions](
		t,
		(*Client).CreateServer,
		newResource,
		"server",
		"POST",
		path.Join("servers"),
		"{}",
	)
	assert.Equal(t, instance.ID, "srv-lv426")
}

func TestUpdateServer(t *testing.T) {
	updatedResource := ServerOptions{ID: "srv-lv426"}
	instance := testModify[Server, ServerOptions](
		t,
		(*Client).UpdateServer,
		updatedResource,
		"server",
		"PUT",
		path.Join("servers", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}

func TestDestroyServer(t *testing.T) {
	deletedResource := testModify[Server, string](
		t,
		(*Client).DestroyServer,
		"srv-lv426",
		"server",
		"DELETE",
		path.Join("servers", "srv-lv426"),
		"",
	)
	assert.Equal(t, deletedResource.ID, "srv-lv426")
}

func TestLockServer(t *testing.T) {
	lockedResource := testModify[Server, string](
		t,
		(*Client).LockServer,
		"srv-lv426",
		"server",
		"PUT",
		path.Join("servers", "srv-lv426", "lock_resource"),
		"",
	)
	assert.Equal(t, lockedResource.ID, "srv-lv426")
}

func TestUnlockServer(t *testing.T) {
	unlockedResource := testModify[Server, string](
		t,
		(*Client).UnlockServer,
		"srv-lv426",
		"server",
		"PUT",
		path.Join("servers", "srv-lv426", "unlock_resource"),
		"",
	)
	assert.Equal(t, unlockedResource.ID, "srv-lv426")
}

func TestServerCreatedAtUnix(t *testing.T) {
	tm := time.Date(2009, time.November, 10, 23, 0, 0, 0, time.UTC)
	target := Server{CreatedAt: &tm}
	assert.Equal(t, target.CreatedAtUnix(), tm.Unix())
}
