// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"
	"time"

	"gotest.tools/v3/assert"
)

func TestUsers(t *testing.T) {
	instance := testAll(
		t,
		(*Client).Users,
		"User",
		"users",
		"Users",
	)
	assert.Equal(t, instance.ID, "usr-kl435")
}

func TestUser(t *testing.T) {
	instance := testInstance(
		t,
		(*Client).User,
		"User",
		path.Join("users", "usr-kl435"),
		"user",
		"usr-kl435",
	)
	assert.Equal(t, instance.ID, "usr-kl435")
}

func TestUpdateUser(t *testing.T) {
	updatedResource := UserOptions{ID: "usr-kl435"}
	instance := testModify(
		t,
		(*Client).UpdateUser,
		updatedResource,
		"user",
		"PUT",
		path.Join("users", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}

func TestUserCreatedAtUnix(t *testing.T) {
	tm := time.Date(2009, time.November, 10, 23, 0, 0, 0, time.UTC)
	target := User{CreatedAt: &tm}
	assert.Equal(t, target.CreatedAtUnix(), tm.Unix())
}
