// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/assert"
)

func TestUsers(t *testing.T) {
	instance := testAll[User](
		t,
		(*Client).Users,
		"User",
		"users",
		"Users",
	)
	assert.Equal(t, instance.ID, "usr-kl435")
}

func TestUser(t *testing.T) {
	instance := testInstance[User](
		t,
		(*Client).User,
		"User",
		path.Join("users", "usr-kl435"),
		"user",
		"usr-kl435",
	)
	assert.Equal(t, instance.ID, "usr-kl435")
}

func TestUpdateUser(t *testing.T) {
	updatedResource := UserOptions{ID: "usr-kl435"}
	instance := testModify[User, UserOptions](
		t,
		(*Client).UpdateUser,
		&updatedResource,
		"user",
		"PUT",
		path.Join("users", updatedResource.ID),
		"{}",
	)
	assert.Equal(t, instance.ID, updatedResource.ID)
}
