// Code generated by go generate; DO NOT EDIT.

package brightbox

import (
	"path"
	"testing"

	"gotest.tools/v3/assert"
)

func TestZones(t *testing.T) {
	instance := testAll[Zone](
		t,
		(*Client).Zones,
		"Zone",
		"zones",
		"Zones",
	)
	assert.Equal(t, instance.ID, "zon-328ds")
}

func TestZone(t *testing.T) {
	instance := testInstance[Zone](
		t,
		(*Client).Zone,
		"Zone",
		path.Join("zones", "zon-328ds"),
		"zone",
		"zon-328ds",
	)
	assert.Equal(t, instance.ID, "zon-328ds")
}

func TestZoneByHandle(t *testing.T) {
	instance := testInstance[Zone](
		t,
		(*Client).Zone,
		"Zone",
		path.Join("zones", "zon-328ds"),
		"zone",
		"zon-328ds",
	)
	assert.Equal(t, instance.ID, "zon-328ds")
	handleInstance := testInstance[Zone](
		t,
		(*Client).ZoneByHandle,
		"Zone",
		path.Join("zones"),
		"zones",
		instance.Handle,
	)
	assert.Equal(t, instance.ID, handleInstance.ID)
}
