// Code generated by generate_enum; DO NOT EDIT.

package transportprotocol

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// Status is an enumerated type
type Status uint8

const (
	// Tcp is an enumeration for transportprotocol.Status
	Tcp Status = iota + 1
	// Udp is an enumeration for Status
	Udp
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Tcp.String(),
	Udp.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "tcp":
		return Tcp, nil
	case "udp":
		return Udp, nil
	}
	var zero Status
	return zero, fmt.Errorf("%s is not a valid transportprotocol.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Tcp:
		return []byte("tcp"), nil
	case Udp:
		return []byte("udp"), nil
	}
	return nil, fmt.Errorf("%d is not a valid transportprotocol.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return &json.UnmarshalTypeError{
			Value: name,
			Type:  reflect.TypeOf(i),
		}
	}
	*i = tmp
	return nil
}
