// Code generated by generate_enum; DO NOT EDIT.

package permissionsgroup

import "fmt"

// Status is an enumerated type
type Status uint8

const (
	// Full is an enumeration for permissionsgroup.Status
	Full Status = iota + 1
	// Storage is an enumeration for Status
	Storage
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Full.String(),
	Storage.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "full":
		return Full, nil
	case "storage":
		return Storage, nil
	}
	return Status(0), fmt.Errorf("%s is not a valid permissionsgroup.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Full:
		return []byte("full"), nil
	case Storage:
		return []byte("storage"), nil
	}
	return nil, fmt.Errorf("%d is not a valid permissionsgroup.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*i = tmp
	return nil
}
