// Code generated by generate_enum; DO NOT EDIT.

package balancingpolicy

import "fmt"

// Status is an enumerated type
type Status uint8

const (
	// LeastConnections is an enumeration for balancingpolicy.Status
	LeastConnections Status = iota + 1
	// RoundRobin is an enumeration for Status
	RoundRobin
	// SourceAddress is an enumeration for Status
	SourceAddress
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	LeastConnections.String(),
	RoundRobin.String(),
	SourceAddress.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "least-connections":
		return LeastConnections, nil
	case "round-robin":
		return RoundRobin, nil
	case "source-address":
		return SourceAddress, nil
	}
	return Status(0), fmt.Errorf("%s is not a valid balancingpolicy.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case LeastConnections:
		return []byte("least-connections"), nil
	case RoundRobin:
		return []byte("round-robin"), nil
	case SourceAddress:
		return []byte("source-address"), nil
	}
	return nil, fmt.Errorf("%v is not a valid balancingpolicy.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*i = tmp
	return nil
}
