// Code generated by generate_enum; DO NOT EDIT.

package volumetype

import "fmt"

// Status is an enumerated type
type Status uint8

const (
	// Image is an enumeration for volumetype.Status
	Image Status = iota + 1
	// Volume is an enumeration for Status
	Volume
	// Raw is an enumeration for Status
	Raw
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Image.String(),
	Volume.String(),
	Raw.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "image":
		return Image, nil
	case "volume":
		return Volume, nil
	case "raw":
		return Raw, nil
	}
	return Status(0), fmt.Errorf("%s is not a valid volumetype.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Image:
		return []byte("image"), nil
	case Volume:
		return []byte("volume"), nil
	case Raw:
		return []byte("raw"), nil
	}
	return nil, fmt.Errorf("%d is not a valid volumetype.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*i = tmp
	return nil
}
