// Code generated by generate_enum; DO NOT EDIT.

package databaseserver

import "fmt"

// Status is an enumerated type
type Status uint8

const (
	// Creating is an enumeration for databaseserver.Status
	Creating Status = iota
	// Active is an enumeration for Status
	Active
	// Deleting is an enumeration for Status
	Deleting
	// Deleted is an enumeration for Status
	Deleted
	// Failing is an enumeration for Status
	Failing
	// Failed is an enumeration for Status
	Failed
)

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "creating":
		return Creating, nil
	case "active":
		return Active, nil
	case "deleting":
		return Deleting, nil
	case "deleted":
		return Deleted, nil
	case "failing":
		return Failing, nil
	case "failed":
		return Failed, nil
	}
	return Status(0), fmt.Errorf("%s is not a valid databaseserver.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Creating:
		return []byte("creating"), nil
	case Active:
		return []byte("active"), nil
	case Deleting:
		return []byte("deleting"), nil
	case Deleted:
		return []byte("deleted"), nil
	case Failing:
		return []byte("failing"), nil
	case Failed:
		return []byte("failed"), nil
	}
	return nil, fmt.Errorf("%v is not a valid databaseserver.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*i = tmp
	return nil
}
