// Code generated by generate_enum; DO NOT EDIT.

package server

import "fmt"

// Status is an enumerated type
type Status uint8

const (
	// Creating is an enumeration for server.Status
	Creating Status = iota + 1
	// Active is an enumeration for Status
	Active
	// Inactive is an enumeration for Status
	Inactive
	// Deleting is an enumeration for Status
	Deleting
	// Deleted is an enumeration for Status
	Deleted
	// Failed is an enumeration for Status
	Failed
	// Unavailable is an enumeration for Status
	Unavailable
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Creating.String(),
	Active.String(),
	Inactive.String(),
	Deleting.String(),
	Deleted.String(),
	Failed.String(),
	Unavailable.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "creating":
		return Creating, nil
	case "active":
		return Active, nil
	case "inactive":
		return Inactive, nil
	case "deleting":
		return Deleting, nil
	case "deleted":
		return Deleted, nil
	case "failed":
		return Failed, nil
	case "unavailable":
		return Unavailable, nil
	}
	return Status(0), fmt.Errorf("%s is not a valid server.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Creating:
		return []byte("creating"), nil
	case Active:
		return []byte("active"), nil
	case Inactive:
		return []byte("inactive"), nil
	case Deleting:
		return []byte("deleting"), nil
	case Deleted:
		return []byte("deleted"), nil
	case Failed:
		return []byte("failed"), nil
	case Unavailable:
		return []byte("unavailable"), nil
	}
	return nil, fmt.Errorf("%d is not a valid server.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return err
	}
	*i = tmp
	return nil
}
