// Code generated by generate_enum; DO NOT EDIT.

package sourcetrigger

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// Status is an enumerated type
type Status uint8

const (
	// Manual is an enumeration for sourcetrigger.Status
	Manual Status = iota + 1
	// Schedule is an enumeration for Status
	Schedule
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Manual.String(),
	Schedule.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "manual":
		return Manual, nil
	case "schedule":
		return Schedule, nil
	}
	var zero Status
	return zero, fmt.Errorf("%s is not a valid sourcetrigger.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Manual:
		return []byte("manual"), nil
	case Schedule:
		return []byte("schedule"), nil
	}
	return nil, fmt.Errorf("%d is not a valid sourcetrigger.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return &json.UnmarshalTypeError{
			Value: name,
			Type:  reflect.TypeOf(i),
		}
	}
	*i = tmp
	return nil
}
