// Code generated by generate_enum; DO NOT EDIT.

package mode

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// Status is an enumerated type
type Status uint8

const (
	// Nat is an enumeration for mode.Status
	Nat Status = iota + 1
	// Route is an enumeration for Status
	Route
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Nat.String(),
	Route.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "nat":
		return Nat, nil
	case "route":
		return Route, nil
	}
	var zero Status
	return zero, fmt.Errorf("%s is not a valid mode.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Nat:
		return []byte("nat"), nil
	case Route:
		return []byte("route"), nil
	}
	return nil, fmt.Errorf("%d is not a valid mode.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return &json.UnmarshalTypeError{
			Value: name,
			Type:  reflect.TypeOf(i),
		}
	}
	*i = tmp
	return nil
}
