// Code generated by generate_enum; DO NOT EDIT.

package collaboration

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// Status is an enumerated type
type Status uint8

const (
	// Pending is an enumeration for collaboration.Status
	Pending Status = iota + 1
	// Accepted is an enumeration for Status
	Accepted
	// Rejected is an enumeration for Status
	Rejected
	// Cancelled is an enumeration for Status
	Cancelled
	// Ended is an enumeration for Status
	Ended
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Pending.String(),
	Accepted.String(),
	Rejected.String(),
	Cancelled.String(),
	Ended.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "pending":
		return Pending, nil
	case "accepted":
		return Accepted, nil
	case "rejected":
		return Rejected, nil
	case "cancelled":
		return Cancelled, nil
	case "ended":
		return Ended, nil
	}
	var zero Status
	return zero, fmt.Errorf("%s is not a valid collaboration.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Pending:
		return []byte("pending"), nil
	case Accepted:
		return []byte("accepted"), nil
	case Rejected:
		return []byte("rejected"), nil
	case Cancelled:
		return []byte("cancelled"), nil
	case Ended:
		return []byte("ended"), nil
	}
	return nil, fmt.Errorf("%d is not a valid collaboration.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return &json.UnmarshalTypeError{
			Value: name,
			Type:  reflect.TypeOf(*i),
		}
	}
	*i = tmp
	return nil
}
