// Code generated by generate_enum; DO NOT EDIT.

package listenerprotocol

import (
	"encoding/json"
	"fmt"
	"reflect"
)

// Status is an enumerated type
type Status uint8

const (
	// Tcp is an enumeration for listenerprotocol.Status
	Tcp Status = iota + 1
	// Http is an enumeration for Status
	Http
	// Https is an enumeration for Status
	Https
)

// Set of strings that are valid inputs for ParseStatus
var ValidStrings = []string{
	Tcp.String(),
	Http.String(),
	Https.String(),
}

// String makes Status satisfy the Stringer interface
func (i Status) String() string {
	tmp, err := i.MarshalText()
	if err == nil {
		return string(tmp)
	}
	return ""
}

// ParseStatus attempts to convert a string into a Status
func ParseStatus(name string) (Status, error) {
	switch name {
	case "tcp":
		return Tcp, nil
	case "http":
		return Http, nil
	case "https":
		return Https, nil
	}
	var zero Status
	return zero, fmt.Errorf("%s is not a valid listenerprotocol.Status", name)
}

// MarshalText implements the text marshaller method
func (i Status) MarshalText() ([]byte, error) {
	switch i {
	case Tcp:
		return []byte("tcp"), nil
	case Http:
		return []byte("http"), nil
	case Https:
		return []byte("https"), nil
	}
	return nil, fmt.Errorf("%d is not a valid listenerprotocol.Status", i)
}

// UnmarshalText implements the text unmarshaller method
func (i *Status) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseStatus(name)
	if err != nil {
		return &json.UnmarshalTypeError{
			Value: name,
			Type:  reflect.TypeOf(i),
		}
	}
	*i = tmp
	return nil
}
